# Generated by Django 6.0.4 on 2026-04-23 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0002_player_is_skipped_auction'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='sold_points',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='sold_team',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
