# Generated by Django 6.0.4 on 2026-04-25 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0003_player_sold_points_player_sold_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='mobile_number',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
