# Generated by Django 6.0.4 on 2026-04-25 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0006_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='is_purse_locked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='auction',
            name='team_purse_limit',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
